-- SQL to initiate DB structure

-- migration structure
create table db_version(
    version INT NOT NULL PRIMARY KEY,
    applied_on TIMESTAMP NOT NULL
);

INSERT INTO db_version (version, applied_on) 
    VALUES ( 1, CURRENT_TIMESTAMP );

-- --------------------------------------
-- tables DDL
CREATE SCHEMA cv;

CREATE TABLE IF NOT EXISTS cv.contact_info (
    id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    sort_position   INT          NOT NULL DEFAULT -1,
    property        VARCHAR(255) NOT NULL,
    value           VARCHAR(512) NOT NULL
);

INSERT INTO cv.contact_info(sort_position, property, value) VALUES
    (0, 'Location', 'Yerevan'),
    (10, 'Email', 'george.sh.tech+cv@gmail.com'),
    (20, 'LinkedIn', 'linkedin.com/in/george-sv'),
    (30, 'Telegram', 't.me/morkou'),
    (40, 'Phone', '+374091231379'),
    (50, 'Visa', 'Sponsorship Required'),
    (-1, 'Summary', '6+ years in software development providing services for financial systems both from scratch and diving into an existing codebase. Took part in the process of transferring the legacy systems to microservices. I am a backend software engineer (Java, Kotlin) with experience in banking systems providing payments, transfers and accounting features.');

-----
CREATE TABLE IF NOT EXISTS cv.skills (
    id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    sort_position   INT           NOT NULL DEFAULT -1,
    category        VARCHAR(255)  NOT NULL,
    list            VARCHAR(1024) NOT NULL
);

INSERT INTO cv.skills(sort_position, category, list) VALUES
    (0, 'Languages', 'Java, Kotlin, SQL, Python, PL/SQL'),
    (10, 'Methodologies', 'Scrum, Kanban'),
    (20, 'Technologies', 'Spring Boot, Maven, Gradle, JUnit, JMS, ArtemisMQ, Kafka, Docker, OpenShift, Kubernetes, Selenium, Oracle AQ'),
    (30, 'Databases', 'IBM DB2, PostgreSQL, Oracle DB'),
    (40, 'IDE', 'IntelliJ IDEA, VSC, Dbeaver, IBM i Access Client Solutions'),
    (50, 'Tools', 'Git, Jira/Conf., OpenLens, OpenSearch'),
    (60, 'Projects', 'Create Intellij Idea plugin: BroBrowser using Kotlin + Swing');

-----
CREATE TABLE IF NOT EXISTS cv.work_experience (
    id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    company_name    VARCHAR(255)    NOT NULL,
    location        VARCHAR(512)    NOT NULL,
    position        VARCHAR(255)    NOT NULL,
    description     VARCHAR(1024)   NOT NULL,
    tech_list       VARCHAR(1024)   NOT NULL,
    dat             DATE            NOT NULL,
    datto           DATE        DEFAULT NULL
);

INSERT INTO cv.work_experience(company_name, location, position, description, tech_list, dat, datto) VALUES
    ('Branch of Kometa corp.', 'Saint-Petersburg, Russia', 'Optics design engineer', 
        'Research and development, the mechanical design of optical devices for scientific and space applications, leading a group of up to 3 colleagues.', 
        'CAD, CAE, other engineering software',
        '2012-09-01', '2018-09-01'),
    ('Sberbank', 'Saint-Petersburg, Russia', 'Software Engineer', 
        'Providing payments and information about fines and taxes on interaction with government APIs, team of 9. \nDeveloped new functionality in the legacy system that provides subscriptions on fines information for bank customers in the external government system. \nSplit a monolithic system into microservices using the inner proprietary message-driven framework (Akka-like). \nDeveloped one of the subsystems using OpenShift services for new external government API, both from scratch and forking existing service.', 
        'Java, Kotlin, Xslt, Spring, Maven, Git',
        '2019-03-18', '2023-01-31'),
    ('Raiffeisen bank', 'Moscow, Russia (remote from Armenia)', 'Software Engineer', 
        'Providing interaction between western accounting systems and the local one. Team of 15. \nMigrating features to microservice architecture. \nSupport for a mission-critical financial reporting platform.', 
        'Java, Spring, IBM DB2, Gradle, Git, Python',
        '2023-04-10', NULL)
;

-----
CREATE TABLE IF NOT EXISTS cv.education (
    id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    institution_name    VARCHAR(255)   NOT NULL,
    degree              VARCHAR(255)   NOT NULL,
    description         VARCHAR(512)   NOT NULL,
    graduation_year     VARCHAR(10)    NOT NULL
);

INSERT INTO cv.education(institution_name, degree, description, graduation_year) VALUES
    ('The National Research University of Information Technologies, Mechanics and Optics (ITMO University)', 
        'Master`s Degree in Optotechnics', 
        'Department of Applied and Computer Optics', 
        '2006-2012'),
    ('Innopolis University', 
        'Advanced training courses on the topic "Software developer using Java EE technologies"', 
        '', 
        '2019');


