create schema portfolio authorization dba;

CREATE TABLE IF NOT EXISTS portfolio.projects (
    id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    sort_position   INT     DEFAULT -1  NOT NULL,
    title           VARCHAR(255)  NOT NULL,
    description     VARCHAR(4096) NOT NULL,
    technologies    VARCHAR(1024) NOT NULL,
    project_url     VARCHAR(1024),
    repo_url        VARCHAR(1024)
);

CREATE TABLE IF NOT EXISTS portfolio.project_images (
    id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    project_id  INT     NOT NULL,
    image_data  BLOB    NOT NULL,
    FOREIGN KEY (project_id) REFERENCES portfolio.projects(id)
);

-- population
INSERT INTO portfolio.projects(sort_position, title, description, technologies, project_url, repo_url)
    VALUES
    (1, 'BroBrowser', 'Plain sidebar browser to open web pages (with documentation for example).', 'Kotlin, IntelliJ SDK, Java Swing',
    'https://plugins.jetbrains.com/plugin/26234-brobrowser', 'https://github.com/Tuchnyak/brobrowser'),
    (2, 'BroNotes', 'A simple note taken plugin for IntelliJ IDEA', 'Kotlin, IntelliJ SDK, Java Swing',
    'https://plugins.jetbrains.com/plugin/25957-bronotes', 'https://github.com/Tuchnyak/bronotes');

-- update db_version
UPDATE migration.db_version SET version = 3, applied_on = CURRENT_TIMESTAMP;
